### ISSUE TITLE
'Show more options' for date facet looks like its own refine option

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#104]
To see this behavior, run a search and limit to one material type.

The 'show more options' for the date facet is appearing as a separate entry in 'refine my results'.  Present in Chrome and Safari.  Other facets showing 'show more options' where expected.

![showmoreoptions](https://f.cloud.github.com/assets/4661920/1695969/51107174-5ebb-11e3-8b7a-13a883caa0c1.png)

**Comment by bassettsj** [comment]
You're right, this isn't what a user would expect, however I am not sure if I can refactor to account for this edge case very easily. @nestochan would this issues be a blocker for releasing tomorrow?

**Comment by bassettsj** [comment]
![screenshot 2013-12-09 10 09 05](https://f.cloud.github.com/assets/1218420/1705785/8e70ee60-60e4-11e3-9595-d53328027427.png)

**Comment by bassettsj** [comment]
Should be fixed now :smile:

**Comment by nestochan** [comment]
awesome! :clap:

**Comment by jasf-** [comment]
I'm still seeing it though might be only intermittently now.  Seeing it in both Safari and Chrome, and doesn't seem to be a caching issue (still seeing it when using Incognito in Chrome for example).

I'm seeing it with this sequence:
Search 'defenestration'
Limit to books or newspaper articles
'Show more options' with gear showing below the date facet as before

Looks eggscellent when it's working though!

**Comment by bassettsj** [comment]
Well it is under a development view.  Trust me it is fixed. 

Steven

**Comment by bassettsj** [comment]
Try using 
http://onesearch.northeastern.edu/primo_library/libweb/action/search.do?vid=NUprod

Steven

**Comment by jasf-** [comment]
Ah.  Yes.  Looks great – thanks.
